// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_V4PYlHyYtnE0y7f9BL5eVPEh5p1cUQE',
    appId: '1:204779751823:web:64a6858bfb4c610605a3fa',
    messagingSenderId: '204779751823',
    projectId: 'pitt-cs1635-launchpad',
    authDomain: 'pitt-cs1635-launchpad.firebaseapp.com',
    storageBucket: 'pitt-cs1635-launchpad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8PbLEZ4YvSLfrNFfUGBjs1R5UI5ij_G4',
    appId: '1:204779751823:android:8a6b2d6c60825e3005a3fa',
    messagingSenderId: '204779751823',
    projectId: 'pitt-cs1635-launchpad',
    storageBucket: 'pitt-cs1635-launchpad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdNgxvfVBCIpT0zAlPJhEVYzEGCl-vzaY',
    appId: '1:204779751823:ios:6019c50f3eef10e805a3fa',
    messagingSenderId: '204779751823',
    projectId: 'pitt-cs1635-launchpad',
    storageBucket: 'pitt-cs1635-launchpad.firebasestorage.app',
    iosBundleId: 'com.example.apiIntegration',
  );
}
